Play.branch
jenny-moore/csc207-final-project pull request #38
Opened 2023-11-27 21:40 UTC by egajigtera

play completed

2023-11-27 21:54 UTC, mitsukakiyohara requested changes
Can you make sure to remove `target/classes `from your commit? You can do this as follows: 
```
 git rm -r --cached target/classes/ 
 git commit -am "remove target/classes/"
 git push
```

2023-11-27 21:58 UTC, mitsukakiyohara commented on src/entity/Game.java
> +    public Game(){}
Don't think you need this line

2023-11-28 01:14 UTC, arvintoqm approved these changes
Looks good just would recommend deleting the classes that are not being used like for example the presenter, since the audio is being played from the interactor we do not really need a presenter and we should probably also explain that in our presentation why we do need need a presenter as our interactor is playing the song and there is no output data. Maybe even the viewmodel and state are redundant.

2023-11-28 02:31 UTC, mitsukakiyohara reviewed
Overall looks good to me - just curious about one section in the ChooseInteractor (not sure why we have that entire execute() method commented out). Thought we needed it?

2023-11-28 02:31 UTC, mitsukakiyohara commented on src/use_case/choose_genre/ChooseInteractor.java
> +        /*ChooseOutputData outputData = new ChooseOutputData(chooseGenreInputData.getGenre());
just curious why are we commenting this entire section out? is this going to be deleted or something like that?

2023-11-28 02:37 UTC, mitsukakiyohara approved these changes

2023-11-28 20:18 UTC, merged